apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: projeto-korp
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: PBFA97CFB590B2093
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true